import type { Kind } from "./editorTypes";

export const blocks: Array<{ kind: Kind; title: string; description: string; category: string }> = [
  { kind: "schedule", title: "Schedule trigger", description: "Run on a timer", category: "Triggers" },
  { kind: "llm", title: "LLM", description: "Prompt a model", category: "Core blocks" },
  { kind: "transform", title: "Transform", description: "Shape context", category: "Core blocks" },
  { kind: "variable", title: "Variable", description: "Store a reusable value", category: "Core blocks" },
  { kind: "condition", title: "Condition", description: "Route on a value", category: "Control flow" },
  { kind: "repeat_until", title: "Repeat until", description: "Bounded loop", category: "Control flow" },
  { kind: "for_each", title: "For each", description: "Iterate a list", category: "Control flow" },
  { kind: "api", title: "API request", description: "Call a service", category: "API connectors" },
  { kind: "weather_forecast", title: "Weather forecast", description: "Keyless NOAA forecast", category: "API connectors" },
  { kind: "news_headlines", title: "News headlines", description: "Keyless Hacker News", category: "API connectors" },
  { kind: "reddit_headlines", title: "Reddit headlines", description: "Read a subreddit feed", category: "API connectors" },
  { kind: "rss_feed", title: "RSS feed", description: "Read an RSS or Atom feed", category: "API connectors" },
  { kind: "webhook_post", title: "Webhook POST", description: "Send JSON to a service", category: "API connectors" },
  { kind: "http_response", title: "HTTP Response", description: "Return JSON to an event caller", category: "Output connectors" },
  { kind: "mongodb", title: "MongoDB", description: "Read or update collection records", category: "Data connectors" },
  { kind: "mongodb_vector_search", title: "MongoDB Search", description: "Retrieve chunks from a vector search index", category: "Data connectors" },
  { kind: "google_calendar", title: "Google Calendar", description: "Read or manage events", category: "Google connectors" },
  { kind: "google_sheets_append", title: "Append Google Sheet row", description: "Write a row to Sheets", category: "Google connectors" },
  { kind: "google_drive", title: "Google Drive file", description: "Create or write a file", category: "Google connectors" },
  { kind: "google_drive_update", title: "Update Drive file", description: "Write to an existing file", category: "Google connectors" },
  { kind: "gmail_send", title: "Send Gmail", description: "Send through Google Workspace", category: "Google connectors" },
  { kind: "github_repository", title: "GitHub repository", description: "Read repository context", category: "GitHub connectors" },
  { kind: "github_action", title: "GitHub action", description: "Create issue, PR, or comment", category: "GitHub connectors" },
  { kind: "job_search", title: "Job search", description: "Search Adzuna or Jooble", category: "Job connectors" },
  { kind: "erragent", title: "ErrAgent", description: "Plan, debug, and propose workflow changes", category: "Agent connectors" },
  { kind: "resend_email", title: "Send email", description: "Send with Resend", category: "Output connectors" },
  { kind: "csv_create", title: "Create CSV", description: "Export tabular data", category: "Output connectors" },
];

export const configs: Record<Kind, Record<string, unknown>> = {
  llm: { model: "gemini-3.6-flash", prompt: "", temperature: 0.2, max_tokens: undefined, system_instructions: "", json_mode: false, output_key: "response" },
  api: { method: "GET", url: "", headers: {}, body: null, api_key_secret: "", api_key_query_param: "", api_key_header: "", output_key: "api_response" },
  condition: { input_path: "", operator: "exists", value: null, logic: "and", conditions: [] },
  repeat_until: { input_path: "", operator: "exists", value: null, max_iterations: 3 },
  for_each: { items_path: "", item_key: "item", body_node_ids: [], result_key: "items", max_items: 25, continue_on_error: false },
  github_repository: { owner: "", repository: "", connection_id: "", operation: "repository_context", search_query: "", search_limit: 10, include_readme: true, auto_select_files: true, include_paths: ["package.json", "pyproject.toml"], max_files: 12, max_chars: 40000, output_key: "repository_context" },
  resend_email: { from_email: "Patchy <patchy@sonicassistant.com>", to: "", subject: "", body: "", body_type: "text", output_key: "email_response" },
  google_drive: { name: "", content: "", mime_type: "text/plain", folder_id: "", file_id: "", connection_id: "", output_key: "drive_file" },
  google_drive_update: { file_id: "", content: "", mime_type: "text/plain", connection_id: "", output_key: "drive_file" },
  weather_forecast: { output_key: "weather", user_agent: "Circuit workflow builder" },
  news_headlines: { limit: 5, output_key: "news", user_agent: "Circuit workflow builder/1.0" },
  google_sheets_append: { spreadsheet_id: "", range_name: "Sheet1!A:Z", values: [], connection_id: "", output_key: "sheet_append" },
  csv_create: { filename: "export.csv", headers: [], rows: [], output_key: "csv_file" },
  rss_feed: { url: "", limit: 10, output_key: "feed" },
  webhook_post: { url: "", headers: {}, body: {}, output_key: "webhook_response" },
  http_response: { status_code: 200, headers: { "Content-Type": "application/json" }, body: {}, output_key: "http_response" },
  mongodb: { project: "", cluster_name: "", database_name: "", collection_name: "", operation: "find", connection_uri_secret: "", filter: {}, update: {}, limit: 20, output_key: "mongodb_result" },
  mongodb_vector_search: { database_name: "", collection_name: "", index_name: "vector_index", embedding_path: "embedding", query: "", k: 4, max_chunks: 4, strategy: "vector", filter: {}, embedding_model: "models/gemini-embedding-001", embedding_dimensions: 768, connection_uri_secret: "", output_key: "retrieved_context" },
  gmail_send: { to: "", subject: "", body: "", connection_id: "", output_key: "gmail_response" },
  reddit_headlines: { subreddit: "news", sort: "top", limit: 5, user_agent: "CircuitWorkflowBot/1.0 (by u/patchy)", output_key: "reddit" },
  google_calendar: { operation: "list", calendar_id: "primary", event_id: "", time_min: "", time_max: "", max_results: 10, event: {}, connection_id: "", output_key: "calendar" },
  github_action: { action: "create_issue", owner: "", repository: "", issue_number: undefined, title: "", body: "", head: "", base: "main", connection_id: "", output_key: "github_action" },
  job_search: { provider: "adzuna", keywords: "software engineer", location: "Des Moines, IA", radius_miles: 30, remote: false, limit: 25, app_id_secret: "", app_key_secret: "", api_key_secret: "", output_key: "jobs" },
  erragent: { operation: "debug_run", endpoint: "https://www.erragent.onrender.com/api/v1/circuit/architect", goal: "", incident_id: "", api_key_secret: "", timeout_seconds: 30, output_key: "erragent_result" },
  schedule: { trigger_mode: "schedule", event_name: "", interval: "hourly", time_of_day: "", timezone: "UTC", enabled: true, days_of_week: [], weeks_interval: 1, input_values: {}, error_handler_node_id: "", response_node_id: "" },
  variable: { name: "value", value: "" },
  transform: { mappings: { result: "" }, merge_arrays: {} },
};
